apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: my-web-server
        image: gcr.io/curious-memory-322511/my-web-server
        ports:
        - containerPort: 8080
        resources:
          requests:
             max:
               cpu: 800m
             min:
               cpu: 200m
